### PR TITLE
Set up Continuous Integration with Travis CI

### LINKED ISSUE #1: Set up Continuous Integration
Set up Travis CI (and optionally [AppVeyor](https://www.appveyor.com/docs/)) to provide a safety net to catch bugs from future contributions.

### PR DESCRIPTION
**Pull request by ashmaroli**
Resolves #1

### CODE REVIEW

**Comment by ashmaroli** [comment]
CI fails with following output:
```
  1) Failure:
TestFiles#test_gfm_/home/travis/build/kramdown/parser-gfm/test/testcases/backticks_syntax_text_to_html [/home/travis/build/kramdown/parser-gfm/test/test_files.rb:32]:
--- expected
+++ actual
@@ -7,15 +7,9 @@
 <pre><code>Unbalanced bottom heavy
 </code></pre>
 
-<div class=\"language-ruby highlighter-coderay\"><div class=\"CodeRay\">
-  <div class=\"code\"><pre><span class=\"line-numbers\"><a href=\"#n1\" name=\"n1\">1</a></span>language no space
-</pre></div>
-</div>
-</div>
+<pre><code class=\"language-ruby\">language no space
+</code></pre>
 
-<div class=\"language-ruby highlighter-coderay\"><div class=\"CodeRay\">
-  <div class=\"code\"><pre><span class=\"line-numbers\"><a href=\"#n1\" name=\"n1\">1</a></span>language with space
-</pre></div>
-</div>
-</div>
+<pre><code class=\"language-ruby\">language with space
+</code></pre>
 "
```

**Comment by ashmaroli** [comment]
@gettalong Should I rewrite all expectations to use Rouge..?

**Comment by gettalong** [comment]
That should probably be done, yes. I tested the GFM parser before I extracted the syntax highlighter, so it works correctly.

**Comment by ashmaroli** [comment]
I've now set up to test with both Rouge 2.x and Rouge 3.x.
Feel free to make changes directly to this branch if you want.

**Comment by ashmaroli** [comment]
Gentle reminder:
**Knock! knock!**

**Comment by gettalong** [comment]
I'm okay with the changes but please only merge *after* I released kramdown 2.0.0 this weekend.

**Pull request merged**
